const ActionTypes = {
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
  
  GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS',
  GET_ORDERS_FAILED: 'GET_ORDERS_FAILED',
  ADD_ORDERS_SUCCESS: 'ADD_ORDERS_SUCCESS',
  ADD_ORDERS_FAILED: 'ADD_ORDERS_FAILED'
}

export default ActionTypes